version: '2'
services:
  nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
  node1:
    build: ./node
    restart: always
    ports:
        - "3000"
  node2:
    build: ./node
    restart: always
    ports:
        - "3000"
  node3:
    build: ./node
    restart: always
    ports:
        - "3000"